[project]
name = "alraei"
version = "0.1.0"
description = "Philopater Demiana Church Application"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flet>=0.28.1",
]

[tool.flet]
name = "الراعي"
product = "الراعي"
company = "Philopater Demiana Church"

[tool.flet.android]
icon = "src/assets/icon.png"